version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: adb-es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      ES_HEAP_SIZE: 2g
      bootstrap.memory_lock: "true"
      ELASTIC_PASSWORD: 3WnQtogV2Tf9h4kjQ5hPAAKeg6jwypVFPSJNm6iaTE5QMTcYavg4tKph8eb6
      cluster.name: "dockercluster"
      node.name: "node-master"
      xpack.security.enabled: "true"
    volumes:
      - adb-esdata:/usr/share/elasticsearch/data
      - adb-essynonyms-volume:/usr/share/elasticsearch/config/analysis
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - my-network
  db:
    image: postgres:12
    networks:
      - my-network
    environment:
      POSTGRES_DB: adb
      POSTGRES_PASSWORD: changeme
    volumes:
      - adb-pgdata-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  adb-pgdata-volume:
    external: true  # docker volume create --name=adb-pgdata-volume
    name: adb-pgdata-volume
  adb-esdata:
    external: true  # docker volume create --name=adb-esdata-volume
    name: adb-esdata-volume
  adb-essynonyms-volume:
    external: true  # docker volume create --name=adb-essynonyms-volume
    name: adb-essynonyms-volume
