@address={{elasticSearchServerAddress}}

###

GET {{address}}/_cat/indices

###

GET {{address}}/_cluster/health?pretty

###

GET {{address}}/s_adb_people_v1/_doc/a-fraile

###

GET {{address}}/s_adb_people_v1/_settings

###
# scalingo, reset the index state
PUT {{address}}/s_adb_people_v1/_settings
Content-Type: application/json

{
  "index": {
    "blocks": {
      "read_only_allow_delete": "false"
    }
  }
}

###
GET {{address}}/s_adb_people_v1

###
# count all the documents in the index
GET {{address}}/s_adb_people_v1/_search
Content-Type: application/json

{
      "_source": {
        "include": [ "fullname" ],
        "exclude": [ "texts", "texts_cut" ]
    },
  "query": {
    "match_all": {}
  }
}

###
DELETE {{address}}/s_adb_people_v1
Content-Type: application/json

###

DELETE {{address}}/s_adb_people_v1/_doc/None

###
# test the software 
@query_string = fragile

GET {{address}}/s_adb_people_v1/_search
Content-Type: application/json

<@ configuration/query.json

###

GET {{address}}/s_adb_people_v1/_search
Content-Type: application/json

{
  "_source": {
    "includes": [
      "fullname",
      "keywords.keyword",
      "keywords.count",
      "texts_cut"
    ]
  },
  "query": {
    "bool": {
      "should": [
        {
          "match": {
              "fullname": {"query": "{{query_string}}", "boost": 2}
          }
        },
        {
          "fuzzy": {
              "fullname": {"value": "{{query_string}}", "boost": 1.2}
          }
        },
        {
          "match": {
            "texts": {
              "query": "{{query_string}}",
              "analyzer": "search_synonyms"
            }
          }
        },
        {
          "nested": {
            "path": "keywords",
            "score_mode": "sum",
            "query": {
              "function_score": {
                "query": {
                  "match": {
                    "keywords.keyword": "{{query_string}}"
                  }
                },
                "field_value_factor": {
                  "field": "keywords.count"
                }
              }
            }
          }
        }
      ],
      "minimum_should_match": 1
    }
  },
  "highlight": {
    "require_field_match": false,
    "fields": {
      "texts_cut": {
        "pre_tags": "<strong>",
        "post_tags": "</strong>"
      }
    }
  },
    "suggest": {
    "text": "{{query_string}}",
    "suggest-1": {
      "term": {
        "field": "fullname"
      }
    },
    "suggest-2": {
      "term": {
        "field": "keywords.keyword"
      }
    }
  }
}

###
GET {{address}}/s_adb_people_v1/_explain/jules-hugot
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
              "author": {
                  "query": "{{query_string}}",
                  "boost": 2
              }
          }
        },
        {
          "match": {
            "texts": {
              "query": "{{query_string}}",
              "analyzer": "search_synonyms"
            }
          }
        },
        {
          "nested": {
            "path": "keywords",
            "score_mode": "sum",
            "query": {
              "function_score": {
                "query": {
                  "match": {
                    "keywords.keyword": "{{query_string}}"
                  }
                },
                "field_value_factor": {
                  "field": "keywords.count"
                }
              }
            }
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
###

PUT {{address}}/s_adb_people_v1
Content-Type: application/json

< configuration/index_settings.json

###

POST {{address}}/_reindex
Content-Type: application/json

{
  "source": {
    "index": "s_adb_people_v1"
  },
  "dest": {
    "index": "s_adb_people_v2"
  }
}
