@address={{elasticSearchServerAddress}}
@index=s_adb_people_v2

# Photos by <a href="https://generated.photos/">Generated Photos</a>
GET https://api.generated.photos/api/v1/faces?age=adult&emotion=joy&per_page=100&page=2
Authorization: API-Key {{generatedPhotosApiKey}}

###

GET {{address}}/signal/_search?size=50
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "sort" : [
    { "timestamp" : {"order" : "desc"}}
  ]
}

###
GET {{address}}/_cat/indices

###

GET {{address}}/_cluster/health?pretty

###

GET {{address}}/{{index}}

###

GET {{address}}/{{index}}/_settings

###
# scalingo, reset the index state
PUT {{address}}/{{index}}/_settings
Content-Type: application/json

{
  "index": {
    "blocks": {
      "read_only_allow_delete": "false"
    }
  }
}

###
GET {{address}}/{{index}}

###
# count all the documents in the index
GET {{address}}/{{index}}/_search
Content-Type: application/json

{
      "_source": {
        "includes": [ "fullname" ],
        "excludes": [ "texts", "texts_cut" ]
    },
  "query": {
    "match_all": {}
  }
}

###
DELETE {{address}}/{{index}}
Content-Type: application/json

###

DELETE {{address}}/{{index}}/_doc/None

###
# test the software 
@query_string = python

GET {{address}}/{{index}}/_search
Content-Type: application/json

<@ configuration/query.json

###
# test the software 

GET {{address}}/{{index}}/_search
Content-Type: application/json

{
  "query": {
    "match": {
        "tags.text": {
            "query": "python",
            "boost": 50
        }
    }
  }
}

###
@doc_id = t-iwaki
GET {{address}}/{{index}}/_doc/{{doc_id}}

###
GET {{address}}/{{index}}/_doc/{{doc_id}}/_explain
Content-Type: application/json

<@ configuration/query.json

###
GET {{address}}/{{index}}/_doc/{{doc_id}}/_explain
Content-Type: application/json

{
    "query": {
        "bool": {
            "must_not": {
                "terms": {
                    "documentRole.keyword": [
                        "Vice-President",
                        "Directors",
                        "Director General",
                        "President",
                        "Director"
                    ]
                }
            },
            "should": [
                {
                    "wildcard": {
                        "fullname": {
                            "value": "{{query_string}}",
                            "boost": 0.5
                        }
                    }
                },
                {
                    "match": {
                        "fullname": {
                            "query": "{{query_string}}",
                            "boost": 2
                        }
                    }
                },
                {
                    "fuzzy": {
                        "fullname": {
                            "value": "{{query_string}}",
                            "boost": 1.2
                        }
                    }
                },
                {
                    "match": {
                        "texts": {
                            "query": "{{query_string}}",
                            "operator": "and"
                        }
                    }
                },
                {
                    "match_phrase": {
                        "texts": {
                            "query": "{{query_string}}",
                            "boost": 2
                        }
                    }
                },
                {
                    "match": {
                        "texts": {
                            "query": "{{query_string}}",
                            "analyzer": "search_synonyms"
                        }
                    }
                },
                {
                    "match": {
                        "tags.text.keyword": {
                            "query": "{{query_string}}",
                            "boost": 50
                        }
                    }
                },
                {
                    "nested": {
                        "path": "keywords",
                        "score_mode": "sum",
                        "query": {
                            "function_score": {
                                "query": {
                                    "match": {
                                        "keywords.keyword": "{{query_string}}"
                                    }
                                },
                                "field_value_factor": {
                                    "field": "keywords.count"
                                }
                            }
                        }
                    }
                }
            ],
            "minimum_should_match": 1
        }
    }
}
###

PUT {{address}}/{{index}}
Content-Type: application/json

< configuration/index_settings.json

###

POST {{address}}/_reindex
Content-Type: application/json

{
  "source": {
    "index": "{{index}}"
  },
  "dest": {
    "index": "new_index"
  }
}
