index_format: s_{organization_id}_people_v1
organization_id: adb
search_engines:
  local:
    family: elasticsearch
    url: http://elastic:3WnQtogV2Tf9h4kjQ5hPAAKeg6jwypVFPSJNm6iaTE5QMTcYavg4tKph8eb6@localhost:9200
